apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: bucket-wrapper-charts
    namespace: dev
    files:
    - template-hr-vs.yaml
    - template-hr-rm-resource-catalogue.yaml
    - template-hr-resource-guard.yaml
    - template-cm.yaml
    - template-pvc.yaml
generatorOptions:
  disableNameSuffixHash: true
