---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket-wrapper
  namespace: dev
  labels:
    app.kubernetes.io/instance: bucket-wrapper
    app.kubernetes.io/name: bucket-wrapper
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bucket-wrapper
      app.kubernetes.io/name: bucket-wrapper
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: bucket-wrapper
        app.kubernetes.io/name: bucket-wrapper
    spec:
      serviceAccountName: bucket-wrapper
      containers:
      - name: bucket-wrapper
        #image: 'registry.gitlab.eox.at/eox/hub/bucket-wrapper:0.8.5'
        image: bucket-wrapper-k8s:0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
        env:
        - name: PREFIX_FOR_NAME
          value: "rm-user"
        - name: WORKSPACE_CHARTS_CONFIG_MAP
          value: "bucket-wrapper-charts"
        - name: HELM_CHART_STORAGE_CLASS_NAME
          value: "test"
        - name: AUTH_SERVER_IP
          value: "test"
        - name: CLUSTER_ISSUER
          value: "test"
        - name: AUTH_SERVER_HOSTNAME
          value: "test"
        - name: RESOURCE_CATALOG_VOLUME_STORAGE_TYPE
          value: "test"
        - name: WORKSPACE_SECRET_NAME
          value: "mucho-secreto"
        - name: NAMESPACE_FOR_BUCKET_RESOURCE
          value: "dev"
        - name: WORKSPACE_CONFIG_MAP_NAME
          value: "workspace"
        - name: GIT_REPO_RESOURCE_FOR_HELM_CHART_NAME
          value: "dummy"
        - name: GIT_REPO_RESOURCE_FOR_HELM_CHART_NAMESPACE
          value: "dummy"
        - name: HELM_CHART_NAME
          value: "dummy"
        - name: HELM_CHART_VERSION
          value: "dummy"
        - name: HARBOR_URL
          value: "http://dev-harbor.hub.eox.at"
        - name: HARBOR_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: container-registry-admin
              key: username
        - name: HARBOR_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: container-registry-admin
              key: password
        - name: WORKSPACE_DOMAIN
          value: ""
        - name: S3_ENDPOINT
          value: ""
        - name: S3_REGION
          value: ""
        - name: UMA_CLIENT_SECRET_NAME
          value: "uma"
        - name: UMA_CLIENT_SECRET_NAMESPACE
          value: "uma"
        resources:
          limits:
            cpu: 0.5
            memory: 512Mi
          requests:
            cpu: 0.05
            memory: 128Mi
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
